export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

function getRandomInt(count: number){
  return Math.floor(Math.random()*count);
}

export default function ProductDetailsLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const random = getRandomInt(2);
  if(random === 1){
    throw new Error("Error loading Product");
  }

  return (
    <div>
      {children}
      <h2>Featured products</h2>
    </div>
  );
}

//This layout has children props which corresponds with the ProductDetails page inside page.tsx
// [products] -> page.tsx
