"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import "../style.css";

//
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const navLinks = [
    {name:"Register", href:"/register"},
    {name:"Login", href:"/login"},
    {name:"Forgot-Password", href:"/forgot-password"}
  ]

 
  const pathname = usePathname();
  return (
    <div>
        <h2>Inner layout</h2>
        <div>
          {navLinks.map((link) => {
            const isActive = pathname === link.href || (pathname.startsWith(link.href) && link.href !== "/")
            return (
              <Link className={isActive ? "active" : "not-active"} href={link.href} key={link.name}>{link.name}</Link>
            )
          })}
        </div>
        {children}
    </div>
  );
}

//This layout file is only shared with login and register components and not shared with forgot-password
//http://localhost:3000/register
//http://localhost:3000/login

