import { Metadata } from "next";

export const metadata : Metadata = {
  title: {
    absolute: "",
    default : "Next.js - Abhijeet",
    template: "%s | Abhijeet",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <h1>My Next.js App</h1>
        </header>
        <main>{children}</main>
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          <p>© 2025 My Next.js App</p>
        </footer>
      </body>
    </html>
  );
}
